version: 2

workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - name: Build Debug APK
        script: |
          cd app
          ../gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
